### ISSUE TITLE
Old version disappeared from PyPi, breaking builds that depend on old version

### ISSUE THREAD

**Issue by gitaarik** [Phuker/markdown_link_attr_modifier#2]
Hi there, just a heads up: The 2.0.0 version apparently disappeared from PyPi:

https://pypi.org/project/markdown-link-attr-modifier/#history

Not sure why, but this broke our build. We pin our dependencies on specific versions, so that when our dependencies get updates, that we still use the same old version, so that we don't run into unexpected surprises.

However, when the old version disappears from PyPi, our build breaks, and we still run into an unexpected surprise ;). Typically old versions are not removed, exactly for this reason. So maybe you were unaware of that. So giving you a heads up for that.

There are some exceptions where it is appropriate to remove an old version, like severe security vulnerabilities.

**Comment by Phuker** [comment]
I apologize for the inconvenience. I deleted old versions recently for some reason. Since reuploading the same version is not allowed, please try using the latest version. Please let me know if there are any problems with the latest version.

**Comment by gitaarik** [comment]
Hi @Phuker, yes I already upgraded to the new version, and that seems to work fine. Thanks.
